---
- name: Install python prerequisites (apt)
  ansible.builtin.apt:
    name:
      - wget
      - build-essential
      - libreadline-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
      - libffi-dev
      - zlib1g-dev
    update_cache: true
    state: present
  when: ansible_pkg_mgr == 'apt'
