---
- hosts: all
  vars:
    app_component: trainer
    python_ver: "3.10.4"
    python_install_ubuntu: "apt"
  roles:
    - stop_mdatp
    - setup_disks
    - install_awscli2
    - update_packages
    - install_docker
    - install_python
    - install_app
  become: true
