---
name: Node.js Test
permissions:
  id-token: write
  contents: write
on:
  pull_request:
    branches:
      - '**'
    paths:
      - .github/workflows/nodejs.yml
      - Terraform/modules/new-relic-synthetic/new-relic-checks/**
  # push:
  #   branches:
  #     - "**"
  #   paths:
  #     - ".github/workflows/nodejs.yml"
  #     - "Terraform/modules/new-relic-synthetic/new-relic-checks/**"

jobs:
  validate:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        lambda:
          - Terraform/modules/new-relic-synthetic/new-relic-checks
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.22.7
      - name: Check syntax
        working-directory: ${{ matrix.lambda }}
        run: node -c ./*.js
      - name: Install dependencies
        working-directory: ${{ matrix.lambda }}
        run: npm install
      - name: Run npm ci
        working-directory: ${{ matrix.lambda }}
        run: npm ci
      - name: run rpm run build
        working-directory: ${{ matrix.lambda }}
        run: npm run build --if-present
      - name: run npm test
        working-directory: ${{ matrix.lambda }}
        run: npm test
      - name: Test via eslint
        working-directory: ${{ matrix.lambda }}
        run: ./node_modules/eslint/bin/eslint.js ./*.js
